---
- name: reload systemd
  systemd:
    daemon_reload: true
  when: ansible_service_mgr == "systemd"

- name: stop automation-agent
  service:
    name: '{{ item }}'
    state: stopped
  with_items: '{{ automation_agent_service_names }}'

- name: start automation-agent
  service:
    name: '{{ item }}'
    state: started
  with_items: '{{ automation_agent_service_names }}'

- name: reload automation-agent
  service:
    name: '{{ item }}'
    state: reloaded
  with_items: '{{ automation_agent_service_names }}'

- name: restart automation-agent
  service:
    name: '{{ item }}'
    state: restarted
  with_items: '{{ automation_agent_service_names }}'
